appConfig:
  secretKey: some Secret Key goes here
  webDirs:
    static: /home/bitterlife/rubbish_heap/rubbish/botva/scala/scorm-editor/webApp/backend/resources/buckets-data/web
    frontend: /home/bitterlife/rubbish_heap/rubbish/botva/scala/scorm-editor/out/webApp/frontend/fastOpt/dest
    solver: /home/bitterlife/rubbish_heap/rubbish/botva/scala/scorm-editor/out/webApp/bucketSolver/fastOpt/dest
  userRepo: /home/bitterlife/rubbish_heap/rubbish/botva/scala/scorm-editor/webApp/backend/resources/buckets-data/users
  bucketsTaskRepo: /home/bitterlife/rubbish_heap/rubbish/botva/scala/scorm-editor/webApp/backend/resources/buckets-data/bucket-tasks
postgresConfig:
  properties:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    dataSource.user: bucket
    dataSource.password: buckets+passworD!@
    dataSource.databaseName: buckets
    dataSource.portNumber: 5432
    dataSource.serverName: localhost
    connectionTimeout: 30000
